const categoriasDescricao = {
    INFORMACAO: [
      "\n\n►INFORMAÇÃO◄ 🔵\n\nCLIENTE INFORMADO SOBRE:",
      "\n\n1101 📞 ►INFORMAÇÃO - Conexão - Ligação Nova◄\nCLIENTE INFORMADO SOBRE LIGAÇÃO NOVA.",
      "\n\n1101 📞 ►INFORMAÇÃO - Conexão - Ligação Nova◄\nCLIENTE INFORMADO SOBRE LIGAÇÃO NOVA, DENTRO DO PRAZO DA OS.",
      "\n\n1101 📞 ►INFORMAÇÃO - Conexão - Ligação Nova◄\nCLIENTE INFORMADO SOBRE REATIVAÇÃO, DENTRO DO PRAZO DA OS.",
      "\n\n1111 📝 ►INFORMAÇÃO◄\nCLIENTE INFORMADO SOBRE RESPOSTA DE RECLAMAÇÃO.",
      "\n\n1111 ⚡ ►INFORMAÇÃO◄\nCLIENTE INFORMADO SOBRE DANOS ELÉTRICOS.",
      "\n\n1111 ❌ ►INFORMAÇÃO◄\nCLIENTE INFORMADO SOBRE DESLIGAMENTO DEFINITIVO.",
      "\n\n1111 🔧 ►INFORMAÇÃO◄\nCLIENTE INFORMADO SOBRE DESLIGAMENTO PROGRAMADO.",
      "\n\n1103 💡 ►INFORMAÇÃO - Benefícios Tarifários◄\nCLIENTE INFORMADO SOBRE BAIXA RENDA.",
      "\n\n1103 💙 ►INFORMAÇÃO - Benefícios Tarifários◄\nCLIENTE INFORMADO SOBRE O PROGRAMA ENERGIA AZUL PARA PESSOAS COM AUTISMO.",
      "\n\n1115 ☀️ ►INFORMAÇÃO◄\nCLIENTE INFORMADO SOBRE CONTATO DE GERAÇÃO DISTRIBUIDA - ENERGIA SOLAR.",
      "\n\n1106 📃 ►INFORMAÇÃO - Tarifas, Fatura e Cobrança◄\nCLIENTE INFORMADO SOBRE FATURAS.",
      "\n\n1106 📃 ►INFORMAÇÃO - Tarifas, Fatura e Cobrança◄\nCLIENTE INFORMADO SOBRE FATURAS, ENVIO SOMENTE PARA O TITULAR.",
      "\n\n1106 💳 ►INFORMAÇÃO - Tarifas, Fatura e Cobrança◄\nCLIENTE INFORMADO SOBRE PAGAMENTO DE FATURAS.",
      "\n\n1116 🔄 ►INFORMAÇÃO◄\nCLIENTE INFORMADO SOBRE RELIGAÇÃO, DENTRO DO PRAZO DA NOTA.",
      "\n\n1116 📅 ►INFORMAÇÃO◄\nCLIENTE INFORMADO SOBRE O ANDAMENTO DO PEDIDO.",
      "\n\n1116 ⏳ ►INFORMAÇÃO◄\nCLIENTE INFORMADO SOBRE PRAZOS.",
      "\n\n1107 🔌 ►INFORMAÇÃO◄\nCLIENTE INFORMADO SOBRE RELIGAÇÃO.",
      "\n\n1107 🔒 ►INFORMAÇÃO◄\nCLIENTE INFORMADO SOBRE RELIGAÇÃO SOMENTE COM FATURAS VENCIDAS PAGAS.",
      "\n\n1118 🏙️ ►INFORMAÇÃO◄\nCLIENTE INFORMADO SOBRE ILUMINAÇÃO PÚBLICA, COM NÚMERO DE ATENDIMENTO REPASSADO DE ACORDO COM SEU MUNICÍPIO.",
      "\n\n1111 🌳 ►INFORMAÇÃO◄\nCLIENTE INFORMADO SOBRE PODA DE ÁRVORES, RESPONSABILIDADE DOS ÓRGÃOS MUNICIPAIS COMPETENTE DA SUA CIDADE, SENDO ORIENTADO A ENTRAR EM CONTATO COM ESSES ÓRGÃOS.",
      "\n\n1111  ►INFORMAÇÃO◄\nCLIENTE INFORMADO SOBRE O NUMERO DO SETOR DE RETENÇÃO DA ATIVIDADES ASSESORIAS."
    ],
  
  
  
    NEGOCIACAO: [
      "\n\n1111 📄 ►NEGOCIAÇÃO - REQUISITOS ATENDIDOS◄\nCLIENTE SOLICITA NEGOCIAÇÃO, COM MAIS DE 3 FATURAS EM ABERTO, SEM PARCELAMENTO NOS ÚLTIMOS 6 MESES, ENCAMINHADO PARA NEGOCIAÇÃO.",
      "\n\n1108 ❌ ►NEGOCIAÇÃO - REQUISITOS NÃO ATENDIDOS◄\nCLIENTE INFORMADO SOBRE OS REQUISITOS PARA SOLICITAR SUA NEGOCIAÇÃO, QUE SÃO 3 FATURAS OU MAIS E/OU SEM PARCELAMENTO INFERIOR A 6 MESES, FORA DO PERÍODO DE FATURAMENTO.",
      "\n\n1108 ℹ️ ►NEGOCIAÇÃO - INFORMAÇÃO◄\nCLIENTE INFORMADO SOBRE NEGOCIAÇÃO"
    ],
  
  
    SOMENTE_NA_AGENCIA_OU_SITE: [
      "\n\n1111 📄 ►INFORMAÇÃO◄\nCLIENTE INFORMADO SOBRE RELIGAÇÃO, SOMENTE NA AGÊNCIA OU SITE, COM A DOCUMENTAÇÃO NECESSÁRIA DEVIDO A POP-UP DE BLOQUEIO (Religação bloqueada via call center. Ir à agência).",
      "\n\n1111 📄 ►INFORMAÇÃO◄\nCLIENTE INFORMADO SOBRE RECLAMAÇÃO DE FATURA DE CONSUMO NÃO REGISTRADO, SOMENTE NA AGÊNCIA OU SITE, COM CARTA ESCRITA À MÃO E DOCUMENTAÇÃO NECESSÁRIA.",
      "\n\n1111 📄 ►INFORMAÇÃO◄\nCLIENTE INFORMADO SOBRE REATIVAÇÃO, SOMENTE NA AGÊNCIA OU SITE, COM A DOCUMENTAÇÃO NECESSÁRIA.",
      "\n\n1111 📄 ►INFORMAÇÃO◄\nCLIENTE INFORMADO SOBRE LIGAÇÃO NOVA, SOMENTE NA AGÊNCIA OU SITE, COM A DOCUMENTAÇÃO NECESSÁRIA.",
      "\n\n1111 📄 ►INFORMAÇÃO◄\nCLIENTE INFORMADO SOBRE NEGOCIAÇÃO, SOMENTE NA AGÊNCIA OU SITE [PI] OU [AL], COM A DOCUMENTAÇÃO NECESSÁRIA.",
      "\n\n1111 📄 ►INFORMAÇÃO◄\nCLIENTE INFORMADO SOBRE VISTORIA, SOMENTE NA AGÊNCIA OU SITE, COM A DOCUMENTAÇÃO NECESSÁRIA.",
      "\n\n1111 📄 ►INFORMAÇÃO◄\nCLIENTE INFORMADO SOBRE AUMENTO/DIMINUIÇÃO DE CARGA, SOMENTE NA AGÊNCIA OU SITE, COM A DOCUMENTAÇÃO NECESSÁRIA.",
      "\n\n1111 📄 ►INFORMAÇÃO◄\nCLIENTE INFORMADO SOBRE TROCA DE LOCAL DO MEDIDOR, SOMENTE NA AGÊNCIA OU SITE, COM A DOCUMENTAÇÃO NECESSÁRIA.",
      "\n\n1111 📄 ►INFORMAÇÃO◄\nCLIENTE INFORMADO SOBRE TROCA DE MEDIDOR, SOMENTE NA AGÊNCIA OU SITE, COM A DOCUMENTAÇÃO NECESSÁRIA.",
      "\n\n1111 📄 ►INFORMAÇÃO◄\nCLIENTE INFORMADO SOBRE TROCA DE TITULARIDADE, SOMENTE NA AGÊNCIA OU SITE, COM A DOCUMENTAÇÃO NECESSÁRIA.",
      "\n\n1111 📄 ►INFORMAÇÃO◄\nCLIENTE INFORMADO SOBRE TROCA DE RAMAL DE SERVIÇO, SOMENTE NA AGÊNCIA OU SITE, COM A DOCUMENTAÇÃO NECESSÁRIA.",
    ],
  
  
    SOLICITACOES: [
      "\n\n2ª 🌟📄 2ª VIA DE FATURA VIA TELA ÁGIL 📄🌟\n\nCLIENTE SOLICITOU O ENVIO DA(S) FATURA(S) [REFERÊNCIA(S) DA(S) FATURA(S)] AO WHATSAPP DO NÚMERO CITADO NO CAMPO TELEFONE ACIMA.",
      "\n\n2099 📧 ►ENVIO DE FATURA POR E-MAIL◄ 📧\n\nCLIENTE SOLICITA O ENVIO DE FATURA MENSALMENTE POR E-MAIL.\n✅ REALIZADO CONFORME PEDIDO DO CLIENTE.",
      "\n\n2100 🚫 ►CANCELAMENTO DE FATURA POR E-MAIL◄ 🚫\n\nCLIENTE SOLICITA O CANCELAMENTO DO ENVIO DE FATURA POR E-MAIL,\nDESEJA RECEBER NOVAMENTE EM SUA UNIDADE.\n✅ REALIZADO CONFORME PEDIDO DO CLIENTE.",
      "\n\n3015 🛑 ►CANCELAR FATURA POR WHATSAPP◄ 🛑\n\nCLIENTE SOLICITA O CANCELAMENTO DO ENVIO DE FATURA POR WHATSAPP,\nDESEJA RECEBER NOVAMENTE EM SUA UNIDADE.\n✅ REALIZADO CONFORME PEDIDO DO CLIENTE.",
      "\n\n2002 📅 ►ALTERAÇÃO DE DATA CERTA◄ 📅\n\nCLIENTE SOLICITA MUDANÇA PARA DATA CERTA,\n🆗 CLIENTE CONFIRMOU SEUS DADOS.",
      "\n\n💵 ►CADASTRO BAIXA RENDA◄ 💵\n\nNIS► \nRG► \nCPF►  \nCLIENTE SOLICITA CADASTRO NO BAIXA RENDA,\n🔄 CADASTRADO CONFORME PEDIDO, INFORMADO O PRAZO DE 5 DIAS ÚTEIS.",
      "\n\n🔄 ►TROCA COM RELIGAÇÃO◄ 🔄\n\nCLIENTE SOLICITA TROCA COM RELIGAÇÃO,\n⏳ INFORMADO O PRAZO DE 5 DIAS ÚTEIS.",
      "\n\n🎤 2029 ►Gravação Telefônica◄ 🎤\n\n►CLIENTE TITULAR, SOLICITA GRAVAÇÕES DE LIGAÇÕES.\n\nPROTOCOLO: \n\n📅 DATA: HORA:\n\nMEIO DE COMUNICAÇÃO: CARTA / E-MAIL\n\n🔒 CIENTE DO PRAZO DE 5 DIAS ÚTEIS.",
      "\n\n🔄 ►REATIVAÇÃO DA NOTA◄ 🔄\n\nCLIENTE SOLICITA REATIVAÇÃO DE NOTA S.O.\nNOTA► \nMOTIVO► PENDENCIA REGULARIZADA",
    ],
  
  
    RELIGACAO: [
      "\n\n2043 🔄 ►RELIGAÇÃO COMUM◄\nPOP-UP DE RELIGAÇÃO DE CONFIANÇA FOI VERIFICADO: ✅ SIM\nSEM PENDÊNCIAS NO SISTEMA E SEM RELIGAÇÃO AUTOMÁTICA GERADA\n\n▼▼ 📅 PRAZO DE RELIGAÇÃO ▼▼\n[X] 24H ZONA URBANA\n[ ] 48H ZONA RURAL\n\n🔍 ENTRADA DE PARCELAMENTO: NÃO\n🔒 FATURA CNR: NÃO\n🚫 FATURA BLOQUEADA: NÃO\n💰 SERVIÇO TAXADO: Monofásico R$10,27 (CLIENTE CIENTE DO VALOR)\n\n✔️ CLIENTE CONFIRMA PAGAMENTO DE VIAS:\n► TODAS AS FATURAS PAGAS NO SISTEMA\n\n",
      "\n\n2044 ⚡ ►RELIGAÇÃO URGENTE◄\nPOP-UP DE RELIGAÇÃO DE CONFIANÇA FOI VERIFICADO: ✅ SIM\nSEM PENDÊNCIAS NO SISTEMA E SEM RELIGAÇÃO AUTOMÁTICA GERADA\n\n▼▼ 📅 PRAZO DE RELIGAÇÃO ▼▼\n[X] 4H URGENTE URBANA\n[ ] 8H URGENTE RURAL\n\n🔍 ENTRADA DE PARCELAMENTO: NÃO\n🔒 FATURA CNR: NÃO\n🚫 FATURA BLOQUEADA: NÃO\n💰 SERVIÇO TAXADO: Monofásico R$10,27 (CLIENTE CIENTE DO VALOR)\n\n✔️ CLIENTE CONFIRMA PAGAMENTO DE VIAS:\n► TODAS AS FATURAS PAGAS NO SISTEMA\n\n"
    ],
  
  
    RECLAMACAO: [
        "\n\n💰 3005 ►RECLAMAÇÃO DE VALORES◄ 💰\n\n🔍 DESCRIÇÃO DA RECLAMAÇÃO: RECLAMA DA FATURA NO VALOR DE [VALOR]\n\n📝 ANÁLISE DO ATENDENTE: A FATURA REFERE-SE AO CONSUMO DE ACORDO COM O SEU HISTÓRICO.\n\n▼▼ FORMA DE RESPOSTA ▼▼ \n📞 TELEFONE (x)  \n✉️ CARTA ( )  \n📧 E-MAIL ( )  \n\n✅ AUTORIZA TERCEIROS: SIM [ ] NÃO [X]",
        "\n\n🔴 ► RECLAMAÇÃO DE ERRO DE LEITURA ◄ \n\n📊 LEITURA ATUAL► \n\n📋 LEITURA QUE CONSTA NO COLETOR / DATA DE COLETA► \n\n🔧 REMEDIAÇÃO PRETENDIDA► \n\n🔍 ANÁLISE DO ATENDENTE► \n\n📞 FORMA DE RESPOSTA►  TELEFONE ( )  CARTA ( )  E-MAIL ( )\nQUAL► __________ \n\n✅ AUTORIZA TERCEIROS? ► SIM ( ) NÃO (x) \n\n📞 TELEFONE (DDD) / NOME E PARENTESCO► \n\n💬 EM CASO DE CORREÇÃO DA CONTA RECLAMADA, CLIENTE AUTORIZA ENVIO DA FATURA VIA WHATSAPP►  SIM (X) NÃO ( ) \n\n📄 INFORMAÇÕES COMPLEMENTARES►",
        "\n\n🔴 RECLAMAÇÃO DO CLIENTE: [CLIENTE RECLAMA SOBRE A SITUAÇÃO...] \n\n🔍 ANÁLISE DO ATENDENTE: DE ACORDO COM O SISTEMA, AQUI ESTÃO OS DETALHES RELEVANTES [...] \n\n↓↓ MEIO DE RESPOSTA DA RECLAMAÇÃO ↓↓ \n[ ] 📧 E-MAIL \n[ ] ✉️ CARTA \n[X] 📞 TELEFONE \n\n✅ AUTORIZA TERCEIROS: SIM [ ] NÃO [X] \n\n",
        "\n\n🔴 ►RECLAMAÇÃO DE ENVIO DE FATURA◄\n\nRECLAMAÇÃO DO CLIENTE: CLIENTE RECLAMA QUE NÃO ESTÃO ENTREGANDO AS FATURAS EM SUA RESIDENCIA \n\n🔍 ANÁLISE DO ATENDENTE: DE ACORDO COM O SISTEMA, ENVIO PELA EMPREITEIRA \n\n↓↓ MEIO DE RESPOSTA DA RECLAMAÇÃO ↓↓ \n[ ] 📧 E-MAIL \n[ ] ✉️ CARTA \n[X] 📞 TELEFONE \n\n✅ AUTORIZA TERCEIROS: SIM [ ] NÃO [X] \n\n",
    ],
    
    NIVEL_DE_TENSAO: [
      "\n\n⚡️▼▼▼ NÍVEL DE TENSÃO ▼▼▼⚡️\n\nCLIENTE INFORMA QUE ESTÃO OCORRENDO OSCILAÇÕES NO FORNECIMENTO DE ENERGIA HÁ MAIS DE 7 DIAS.\n\n1. ⏳ HÁ QUANTO TEMPO O PROBLEMA VEM ACONTECENDO? ► +7 DIAS\n2. ⚡️ A SUA ENERGIA FALTA E VOLTA RAPIDAMENTE? ► NÃO\n3. 🕒 EXISTE HORÁRIO ESPECÍFICO PARA OSCILAÇÃO DE SUA ENERGIA ELÉTRICA? ► 24H\n4. 🏭 EXISTE INDÚSTRIA OU COMÉRCIO PRÓXIMO? ► NÃO\n5. 👥 VIZINHOS RECLAMAM DO MESMO PROBLEMA? ► NÃO"
    ],
  
    
    DESLIGAMENTO: [
      "\n\n2090 🔌 ▼▼▼ DESLIGAMENTO DEFINITIVO COM OU SEM LEITURA ▼▼▼ 🔌\n\nCLIENTE TITULAR DA CC SOLICITA DESLIGAMENTO DEFINITIVO.\n📝 Ciente da fatura de consumo final e do prazo de 30 dias para a equipe retirar o equipamento. Dentro desse prazo, o cliente não consegue solicitar uma ligação nova e deve ir retirar a fatura na agência mais próxima.\n\n🏷️ MOTIVO ► IMÓVEL FECHADO.\n✅ AUTORIZA FATURAMENTO POR MÉDIA.\n💰 CLIENTE CIENTE DO VALOR DE R$ XXXXXXX EM ABERTO NESSA CC."
    ],
  
    
    CANCELAMENTO_BAIXA_RENDA: [
      "\n\n🛑▼▼▼ CANCELAMENTO BAIXA RENDA ▼▼▼🛑\n\n📋 CPF►  \n🆔 RG►  \n🔢 NIS►  \n📅 DATA DE NASCIMENTO►  \n\nCLIENTE SOLICITA CANCELAMENTO DO BAIXA RENDA DESSA U.C.\n⏳ PRAZO INFORMADO► 5 DIAS ÚTEIS"
    ],
    
    DANOS_ELETRICOS: [
      "\n\n⚡️▼▼▼ DANOS ELÉTRICOS ▼▼▼⚡️\n\n🆔 RG►  \n📋 CPF►  \n\n🔧 DECLARA DANOS EM SEUS APARELHOS ELÉTRICOS\n📝 DESCRIÇÃO► OSCILAÇÃO CONSTANTE\n📅 DATA►  \n🕒 HORÁRIO►  \n\n📋 INFORMAÇÕES\n📡 ANTENA PARABÓLICA? ► NÃO\n📞 TELEFONE FIXO? ► NÃO\n🌧️ ESTAVA CHOVENDO? ► NÃO\n🛠️ HAVIA EQUIPE TÉCNICA NO LOCAL? ► NÃO\n🏠 ATINGIU OUTRAS RESIDÊNCIAS? ► NÃO\n⚡ NESTE MOMENTO A INSTALAÇÃO ESTÁ SEM ENERGIA? ► NÃO\n\n▼▼▼ APARELHO(S) ▼▼▼\n\n📱 APARELHO►  \n🏷️ MARCA►  \n📦 MODELO►  \n⏳ TEMPO DE USO►  \n🧾 TEM NOTA FISCAL DO APARELHO? ► NÃO\n\n💵 SOLUÇÃO PRETENDIDA ► VALOR RESSARCIDO\n\n▼▼▼ FORMA DE ENVIO DA RESPOSTA ▼▼▼\n📞 TELEFONE ►  \n📧 E-MAIL ►  \n👤 PESSOA(S) AUTORIZADA(S) A RECEBER A RESPOSTA? NÃO\n💳 FORMA DE RESSARCIMENTO ► CONTA POUPANÇA"
    ],
  
    
    DANOS_MATERIAIS: [
      "\n\n🛠️▼▼▼ DANOS MATERIAIS ▼▼▼🛠️\n\n🔍 RECLAMA QUE ►  \n📅 DATA►  \n🕒 HORÁRIO►  \n🐾 HOUVE A MORTE DE UM ANIMAL DEVIDO A ►  \n🍽️ HOUVE A PERDA DE ALIMENTO DEVIDO A ►  "
    ],
  
    CANCELAMENTO_DE_ATIVIDADES_ACESSORIAS: [
        "🛡️▼▼▼ CLIENTE DESEJA CANCELAMENTO DE ATIVIDADES ACESSORIAS ▼▼▼🛡️\nQUAL ATIVIDADE? ► LAR PROTEGIDO\n💲 VALOR? ► 13,90\n✅ REALIZADO CONFORME PEDIDO DO CLIENTE."
    ],
  
    DENUNCIA_DE_FRAUDE: [
        "\n\n🚨▼▼▼ DENÚNCIA DE FRAUDE ▼▼▼🚨\n\n🕵️ ANÔNIMO\n📝 DESCRIÇÃO:\n🌆 CIDADE:\n🏘️ BAIRRO:\n🏠 RUA:\n🔢 NÚMERO:\n🎨 COR OU CARACTERÍSTICA DA RESIDÊNCIA:\n🔍 CARACTERÍSTICA DA FRAUDE:\n❓ OUTRAS INFORMAÇÕES?"
    ],
  
  
    SERVIÇOS_EMERGENCIAIS: [
      "\n\n🚨🚨🚨 RECHAMADO 🚨🚨🚨\n\nEMERGÊNCIA►► CLIENTE INFORMA QUE CONTINUA COM FALTA DE ENERGIA INDIVIDUAL. PEDE AGILIDADE.",
      "\n\n🚨🚨🚨 RECHAMADO 🚨🚨🚨\n\nEMERGÊNCIA►► CLIENTE INFORMA QUE CONTINUA COM FALTA DE ENERGIA COLETIVA. PEDE AGILIDADE.",
      "\n\n2147 🚨🚨🚨 SERVIÇO EMERGENCIAL 🚨🚨🚨\nEMERGÊNCIA►► CLIENTE INFORMA FALTA DE ENERGIA COLETIVA. PEDE AGILIDADE.",
      "\n\n2148 🚨🚨🚨 SERVIÇO EMERGENCIAL 🚨🚨🚨\nEMERGÊNCIA►► CLIENTE INFORMA FALTA DE ENERGIA INDIVIDUAL. PEDE AGILIDADE.\n🔧 TESTE DO DISJUNTOR REALIZADO? ► SIM",
      "\n\n2151 🚨🚨🚨 SERVIÇO EMERGENCIAL 🚨🚨🚨\nEMERGÊNCIA►► CLIENTE INFORMA REDE BT PARTIDA. PEDE AGILIDADE.\n⚠️ RISCO À VIDA ► SIM",
      "\n\n2152 🚨🚨🚨 SERVIÇO EMERGENCIAL 🚨🚨🚨\nEMERGÊNCIA►► CLIENTE INFORMA REDE MT PARTIDA. PEDE AGILIDADE.\n⚠️ RISCO À VIDA ► SIM",
      "\n\n2048 🚨🚨🚨 SERVIÇO EMERGENCIAL Falta de Energia 🚨🚨🚨\nEMERGÊNCIA►► CLIENTE INFORMA FALTA DE ENERGIA INDIVIDUAL. PEDE AGILIDADE.\n🔧 TESTE DO DISJUNTOR REALIZADO? ► SIM.",
      "\n\n2048 🚨🚨🚨 SERVIÇO EMERGENCIAL Falta de Energia 🚨🚨🚨\nEMERGÊNCIA►► CLIENTE INFORMA FALTA DE ENERGIA INDIVIDUAL, PERDA DE RAMAL. PEDE AGILIDADE.",
      "\n\n2049 🚨🚨🚨 SERVIÇO EMERGENCIAL Rede Partida 🚨🚨🚨\nEMERGÊNCIA►► CLIENTE INFORMA REDE MT PARTIDA. PEDE AGILIDADE.\n⚠️ RISCO À VIDA ► SIM",
      "\n\n2049 🚨🚨🚨 SERVIÇO EMERGENCIAL Rede Partida 🚨🚨🚨\nEMERGÊNCIA►► CLIENTE INFORMA REDE BT PARTIDA. PEDE AGILIDADE.\n⚠️ RISCO À VIDA ► SIM",
      "\n\n2050 🚨🚨🚨 SERVIÇO EMERGENCIAL Falta de Energia Geral 🚨🚨🚨\nEMERGÊNCIA►► CLIENTE INFORMA FALTA DE ENERGIA COLETIVA. PEDE AGILIDADE.",
      "\n\n2051 🚨🚨🚨 SERVIÇO EMERGENCIAL Incêndio/Queimada 🚨🚨🚨\nEMERGÊNCIA►► CLIENTE INFORMA QUE PRÓXIMO À SUA CASA HÁ UM INCÊNDIO NA REDE/POLE E SOLICITA QUE UMA EQUIPE VÁ EM CAMPO PARA NORMALIZAR A SITUAÇÃO.\n⚠️ RISCO À VIDA ► SIM",
      "\n\n2054 🚨🚨🚨 SERVIÇO EMERGENCIAL Choque/Vazamento 🚨🚨🚨\nEMERGÊNCIA►► CLIENTE INFORMA QUE HÁ UM VAZAMENTO DE ENERGIA NO LOCAL. PEDE AGILIDADE.\n⚠️ RISCO À VIDA ► SIM",
      "\n\n2055 🚨🚨🚨 SERVIÇO EMERGENCIAL Ramal de Serviço Partido 🚨🚨🚨\nEMERGÊNCIA►► CLIENTE INFORMA SERVIÇO DE RAMAL PARTIDO. PEDE AGILIDADE.\n⚠️ RISCO À VIDA ► SIM",
      "\n\n2056 🚨🚨🚨 SERVIÇO EMERGENCIAL Faiscamento na Rede 🚨🚨🚨\nEMERGÊNCIA►► CLIENTE INFORMA QUE PRÓXIMO À SUA CASA HÁ UM FAISCAMENTO NA REDE E SOLICITA QUE UMA EQUIPE VÁ EM CAMPO PARA NORMALIZAR A SITUAÇÃO.\n⚠️ RISCO À VIDA ► SIM",
      "\n\n2057 🚨🚨🚨 SERVIÇO EMERGENCIAL Falta de Fase 🚨🚨🚨\nEMERGÊNCIA►► CLIENTE INFORMA FALTA DE FASE EM SUA UNIDADE. PEDE AGILIDADE.\n🔧 TESTE DOS DISJUNTORES REALIZADOS? ► SIM.",
      "\n\n2058 🚨🚨🚨 SERVIÇO EMERGENCIAL 🚨🚨🚨\nEMERGÊNCIA►► CLIENTE INFORMA QUE UM POSTE ESTÁ CAÍDO NO LOCAL. PEDE AGILIDADE.\n⚠️ RISCO À VIDA? ► SIM",
      "\n\n2058 🚨🚨🚨 SERVIÇO EMERGENCIAL 🚨🚨🚨\nEMERGÊNCIA►► CLIENTE INFORMA QUE UM POSTE ESTÁ TORTO/ABARROADO NO LOCAL COM RISCO DE QUEDA. PEDE AGILIDADE.\n⚠️ RISCO À VIDA? ► SIM",
      "\n\n2061 🚨🚨🚨 SERVIÇO EMERGENCIAL 🚨🚨🚨\nEMERGÊNCIA►► CLIENTE INFORMA QUE ESTÃO OCORRENDO OSCILAÇÕES NO FORNECIMENTO DE ENERGIA. PEDE AGILIDADE.\n📊 OSCILAÇÃO GERAL OU INDIVIDUAL? ► INDIVIDUAL\n🕒 HORÁRIO► O DIA TODO.",
      "\n\n🚨🚨🚨 SERVIÇO EMERGENCIAL Reclamação Vão Baixo 🚨🚨🚨\nEMERGÊNCIA►► CLIENTE INFORMA QUE O SEU RAMAL ENCONTRA-SE MUITO BAIXO, OFERECENDO RISCO DE SER PARTIDO."
    ],
  
  
    EQUATORIAL_RESOLVE_PA: [
        "\n\n1111 ▼▼▼TRANSFERÊNCIA PARA RESOLVER PARÁ▼▼▼\n\n► CLIENTE NÃO CONCORDA COM O CONSUMO DA FATURA DE XX/XXXX NO VALOR DE R$XXX,XX. ENCAMINHADO PARA A EQUIPE DO EQTL RESOLVE. ◄"
    ],
  
  };